Allows user to specify search terms and adds Album art from Last.fm
ashishmadeti/spotify-playlist-downloader pull request #6
Opened 2017-03-09 11:40 UTC by g33kyaditya

The current Album Art backend is Last.fm which although works fine is not fine. Hence it is WIP and I will add more backends like MusicBrainz once I know that this is the way to go about it.

Additionally, I'm not sure whether to delete the downloaded images after they have been embedded to the mp3, so I've kept them for now.

An additional command line argument for specifying the search terms as a string has also been provided

2017-03-14 12:51 UTC, ashishmadeti requested changes

2017-03-14 12:51 UTC, ashishmadeti commented on download_from_csv.py
> +    API_KEY = '03f624c25bd2ffdbad319226716efe66'
You should never commit API keys to your code. It should either be an environment variable or a command line argument.

2017-03-14 12:51 UTC, ashishmadeti commented on download_from_csv.py
> +        urlretrieve(image_download, image_path)
Use `requests` library to fetch the image. Do not save the image to the file as you will have to read it from file anyway. Instead, return the image stream from your `download_album_art` method.
That way you can directly set the album art (without the need of a temporary file) in the main script

2017-03-14 12:51 UTC, ashishmadeti commented on download_from_csv.py
> +parser.add_argument('-q', '--query', help="enter the search query", type=str)
Change the tone of the help string.
Help strings generally describe **what the argument** does instead of telling the user **what to do**. (You can confirm this by looking at the myriad of man pages available).
Ex: **number of songs to skip** instead of **enter the number of songs you want to skip**

2017-03-14 12:51 UTC, ashishmadeti commented on download_from_csv.py
> +def download_album_art(song):
It will become ugly when you would like to add more album-art fetchers. So you can do the following:

1. Move this functionality to a different module and import it here
2. Make a several functions, one for each album art backend. like `fetch_from_lastfm`, `fetch_from_google` etc.
3. Create a function which will act as an entry point for all the different backends (See point 2) and will take different parameters depending on the backend the user want to use (You can use [kwargs](http://www.saltycrane.com/blog/2008/01/how-to-use-args-and-kwargs-in-python/))

As users wouldn't bother to get their last.fm API key, add Google Images backend too and set it as default. Doing a query with `<Album name> cover art` gives very good results. Also add a command line argument to switch to last.fm backend (in which case your script will expect an environment variable with the API key)

2017-03-14 12:51 UTC, ashishmadeti commented on download_from_csv.py
> +def download_album_art(song):
You can also think of some other better way to do it.

2017-03-16 12:50 UTC, g33kyaditya commented
Fixed code and made changes according to last review. Added images.google.com as the default album art backend and gave user an option to switch to last.fm if needed.

2017-03-16 13:40 UTC, ashishmadeti requested changes

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +    #print 'Image download link is %s' %image_download
Cleanup

2017-03-16 13:40 UTC, ashishmadeti commented on download_from_csv.py
> +        image = album_art.fetch(song, backend='google')
Reduce the code in your if-else
The only difference between this line and L120 is `backend=<something>`

2017-03-16 13:40 UTC, ashishmadeti commented on download_from_csv.py
> +        if image != None:
`image` is same as `image != None`

Checkout https://docs.python.org/2.4/lib/truth.html

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +        if image.get('size') == 'extralarge':       #The most suitable image size
Point of this if-else ladder?

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +        images = response.get('album', None).get('image', None)
This will result in an `AttributeError` when `response` does not contain the key _album_

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +
Please fix PEP8 errors in all the your changes.

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +
There are pep8 plugins for almost all popular editors or you can install the `pep8` apt package and use it like `pep8 <your file name>` to check if your file conforms to pep8 guidelines.

Only acceptable error is `E501`

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +    if link == None:
`not link`

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +    if link == None:
Try to make your code more elegant.

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +    url = 'https://www.google.com/search?site=&tbm=isch&source=hp&biw=1366&bih=649&q=%s&oq=%s&gs_l=img.3...857.12029.0.12205.36.14.1.20.21.0.301.1337.0j7j0j1.8.0....0...1ac.1.64.img..7.15.1346.0..0j0
Change it to most-minimal url that works.

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +import string
No need for this. All string objects have `replace` member function.

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +    query = song['artist'] + song['name'] + 'cover art google play' # Art work can be of huge size so the 'google play' in query mostly results into smaller images
I don't know on what songs you tested this query on, but when I am testing this it is not showing good results.
Use `'%s %s' % (song['album'], song['artist'])`.

2017-03-16 13:40 UTC, ashishmadeti commented on album_art.py
> +    query = song['artist'] + song['name'] + 'cover art google play' # Art work can be of huge size so the 'google play' in query mostly results into smaller images
Using `%` for concatenating string is more efficient than using `+` and also more readable.
Or even better use `' '.join(<array>)`

2017-03-16 13:40 UTC, ashishmadeti commented on download_from_csv.py
> +    if args.query == None:
Reduce code in if-else.
Think: You are basically using `.join()` on an array. The array can change according to `args.query`

2017-03-16 14:57 UTC, g33kyaditya commented on album_art.py
> +        if image.get('size') == 'extralarge':       #The most suitable image size
We are not sure if there is a extralarge for some image or not, so I download the best possible size among the available ones

2017-03-16 15:00 UTC, ashishmadeti commented on album_art.py
> +        if image.get('size') == 'extralarge':       #The most suitable image size
But you are doing the same thing in bodies of all the _ifs_. Might as well remove them, no?

2017-03-20 16:06 UTC, closed without merging